name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]  # Only trigger on backend changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Render Deploy
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"